#!/bin/bash
FILE=mi_ram
make $FILE
if test -f "./$FILE"; then
    valgrind --log-file="valgrind" --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./$FILE
fi
